Controllers films users
Vladik2023/java-filmorate pull request #4
Opened 2023-10-19 09:52 UTC by Vladik2023

2023-10-19 16:24 UTC, andrew-larkin requested changes
Привет! Очень хороший старт, по структуре все выполнено правильно. Пара правок и сможем двигаться дальше.

2023-10-19 16:24 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService, Validator validator) {
чтобы не создавать конструктор в контроллере, можем поставить над классом @RequiredArgsConstructor - тогда все переменные, помеченные как final автоматически добавятся в неявный конструктор

2023-10-19 16:24 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserController(UserService userService, Validator validator) {
@RequiredArgsConstructor

2023-10-19 16:24 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Data
@Data лучше не использовать для классов-моделей, т.к. она может некорректно рассчитывать хэшкод. Лучше заменить ее другими аннотациями, типа @Getter, @Setter и т.д.

2023-10-20 19:21 UTC, Vladik2023 commented
Исправлены замечания

2023-10-28 18:04 UTC, closed without merging