feat: 1
Vladik2023/java-filmorate pull request #9
Opened 2023-11-06 18:30 UTC by Vladik2023

Добавил друзей и лайки в фильмы. Будем надеется что тут не появится сообщение "HELP"

2023-11-06 20:05 UTC, Vladik2023 commented
у меня почему тосты отвалились, хотя в тот раз работали нормально

2023-11-06 20:32 UTC, andrew-larkin requested changes
Привет! Структура практически правильная, остается немного поменять внедрение зависимостей. И поправить тесты - чтобы они не падали с ошибками во время сборки.

2023-11-06 20:32 UTC, andrew-larkin commented on src/main/java/ru/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
filmStorage должен внедряться в filmService

2023-11-06 20:32 UTC, andrew-larkin commented on src/main/java/ru/practicum/filmorate/controller/UserController.java
> +    private final UserStorage userStorage;
такая же ситуация как и в соседнем контроллере

2023-11-06 20:32 UTC, andrew-larkin commented on src/main/java/ru/practicum/filmorate/controller/FilmController.java
>      private final Validator validator;
валидатор тоже переносим в сервис. в контроллере не должно быть никакой доп логики, кроме вызова метода сервиса

2023-11-06 20:32 UTC, andrew-larkin commented on src/main/java/ru/practicum/filmorate/service/UserService.java
> +    public UserService() {
тут тоже можно не создавать конструктор - достаточно использовать @RequiredArgsConstructor и final

2023-11-12 11:51 UTC, Vladik2023 commented
Снова эти дебильные ошибки в постмане, я прочитал че там и как, даже через переводчик не понятно

2024-01-14 16:40 UTC, merged